export enum ErrorCode {
	UNKNOWN_ERROR = "UNKNOWN_ERROR",
	NETWORK_ERROR = "NETWORK_ERROR",
	REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
	INVALID_RESPONSE = "INVALID_RESPONSE",
	VALIDATION_ERROR = "VALIDATION_ERROR",
	PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND",
	PAYMENT_ALREADY_CANCELLED = "PAYMENT_ALREADY_CANCELLED",
}
